//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;
using CMS.Helpers;

[assembly: RegisterDocumentType(FooterNavigation.CLASS_NAME, typeof(FooterNavigation))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
    /// <summary>
    /// Represents a content item of type FooterNavigation.
    /// </summary>
    public partial class FooterNavigation : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.FooterNavigation";


		/// <summary>
		/// The instance of the class that provides extended API for working with FooterNavigation fields.
		/// </summary>
		private readonly FooterNavigationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FooterNavigationID.
		/// </summary>
		[DatabaseIDField]
		public int FooterNavigationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FooterNavigationID"), 0);
			}
			set
			{
				SetValue("FooterNavigationID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FooterNavigation fields.
		/// </summary>
		[RegisterProperty]
		public FooterNavigationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FooterNavigation fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FooterNavigationFields : AbstractHierarchicalObject<FooterNavigationFields>
		{
			/// <summary>
			/// The content item of type FooterNavigation that is a target of the extended API.
			/// </summary>
			private readonly FooterNavigation mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FooterNavigationFields" /> class with the specified content item of type FooterNavigation.
			/// </summary>
			/// <param name="instance">The content item of type FooterNavigation that is a target of the extended API.</param>
			public FooterNavigationFields(FooterNavigation instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FooterNavigationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FooterNavigationID;
				}
				set
				{
					mInstance.FooterNavigationID = value;
				}
			}


			/// <summary>
			/// Navigation items.
			/// </summary>
			public IEnumerable<TreeNode> NavigationItems
			{
				get
				{
					return mInstance.GetRelatedDocuments("NavigationItems");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FooterNavigation" /> class.
		/// </summary>
		public FooterNavigation() : base(CLASS_NAME)
		{
			mFields = new FooterNavigationFields(this);
		}

		#endregion
	}
}