//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using CMS;
using CMS.Base;

using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(Generator.CLASS_NAME, typeof(Generator))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
    /// <summary>
    /// Represents a content item of type Generator.
    /// </summary>
    public partial class Generator : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.Generator";


		/// <summary>
		/// The instance of the class that provides extended API for working with Generator fields.
		/// </summary>
		private readonly GeneratorFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with Generator fields.
		/// </summary>
		[RegisterProperty]
		public GeneratorFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Generator fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GeneratorFields : AbstractHierarchicalObject<GeneratorFields>
		{
			/// <summary>
			/// The content item of type Generator that is a target of the extended API.
			/// </summary>
			private readonly Generator mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GeneratorFields" /> class with the specified content item of type Generator.
			/// </summary>
			/// <param name="instance">The content item of type Generator that is a target of the extended API.</param>
			public GeneratorFields(Generator instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Generator" /> class.
		/// </summary>
		public Generator() : base(CLASS_NAME)
		{
			mFields = new GeneratorFields(this);
		}

		#endregion
	}
}