//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(StoreSection.CLASS_NAME, typeof(StoreSection))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type StoreSection.
	/// </summary>
	public partial class StoreSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.StoreSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with StoreSection fields.
		/// </summary>
		private readonly StoreSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with StoreSection fields.
		/// </summary>
		[RegisterProperty]
		public StoreSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with StoreSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class StoreSectionFields : AbstractHierarchicalObject<StoreSectionFields>
		{
			/// <summary>
			/// The content item of type StoreSection that is a target of the extended API.
			/// </summary>
			private readonly StoreSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="StoreSectionFields" /> class with the specified content item of type StoreSection.
			/// </summary>
			/// <param name="instance">The content item of type StoreSection that is a target of the extended API.</param>
			public StoreSectionFields(StoreSection instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="StoreSection" /> class.
		/// </summary>
		public StoreSection() : base(CLASS_NAME)
		{
			mFields = new StoreSectionFields(this);
		}

		#endregion
	}
}